analyze_requirements:
  description: "Analyze the user's business requirement: '{business_requirement}'. Extract key features, technologies, and criteria for the ideal open-source project. Create a detailed summary of these requirements."
  expected_output: "A structured summary of the project requirements, including key features, suggested technologies, and evaluation criteria."

research_projects:
  description: "Based on the analyzed requirements, search GitHub for suitable open-source projects. For each project found, gather information on its features, community, activity, and license."
  expected_output: "A list of 10 potential open-source projects, each with a summary of its relevance to the requirements, its GitHub URL, and key statistics (stars, forks, last commit)."

evaluate_projects:
  description: "Evaluate the list of researched projects. For each project, assess its suitability against the original business requirement. Provide a detailed report on the pros and cons of each, and recommend the best fit."
  expected_output: "A final report detailing the evaluation of each project, with a clear recommendation for the most suitable one and a justification for the choice."
